plugins {
    id 'java-library'
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.141'
}

version = '26.2-9.0.3'
group = 'com.ethangallant'

base {
    archivesName = 'mysticalagriculture'
}

java.toolchain.languageVersion = JavaLanguageVersion.of(25)

println "Java: ${System.getProperty 'java.version'}, JVM: ${System.getProperty 'java.vm.version'} (${System.getProperty 'java.vendor'}), Arch: ${System.getProperty 'os.arch'}"

repositories {
    maven {
        name = 'GitHubPackages'
        url = 'https://maven.pkg.github.com/ethan-gallant/Cucumber'

        credentials {
            username = System.getenv('GPR_USER') ?: findProperty('gpr.user')
            password = System.getenv('GPR_TOKEN') ?: findProperty('gpr.key')
        }

        content {
            includeGroup 'com.ethangallant'
        }
    }
    maven { url 'https://maven.blamejared.com' }
    maven { url 'https://maven.tterrag.com' }
    maven {
        url 'https://cursemaven.com'
        content {
            includeGroup 'curse.maven'
        }
    }
    mavenLocal()
}

tasks.register('syncTestDatapacks', Sync) {
    if (file('run/saves').exists()) {
        file('run/saves').eachDir { dir ->
            project.sync {
                from 'src/test/resources/datapacks'
                into file(dir.path + '/datapacks')
            }
        }
    }

    project.sync {
        from 'src/test/resources/datapacks'
        into file('run/world/datapacks')
    }
}

tasks.register('syncTestScripts', Sync) {
    from 'src/test/resources/scripts'
    into 'run/scripts'
}

neoForge {
    version = neo_version

    runs {
        client {
            client()
        }

        server {
            server()
        }

        data {
            clientData()

            programArguments.addAll '--mod', 'mysticalagriculture', '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }

        configureEach {
            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'terminal.jline', 'true'
            logLevel = org.slf4j.event.Level.DEBUG
            ideName = "MysticalAgriculture - ${it.ideName.get()}"
            taskBefore tasks.named('syncTestDatapacks')
            taskBefore tasks.named('syncTestScripts')
        }
    }

    mods {
        mysticalagriculture {
            sourceSet(sourceSets.main)
        }
    }
}

configurations {
    runtimeClasspath.extendsFrom localRuntime
}

sourceSets.main.resources {
    srcDirs 'src/generated/resources'
    exclude '.cache'
}

dependencies {
    implementation "com.ethangallant:cucumber:${cucumber_version}"

    implementation "curse.maven:jade-324717:${jade_version}"
//  implementation "curse.maven:the-one-probe-245211:${top_version}"
//  implementation "com.blamejared.crafttweaker:CraftTweaker-neoforge-${crafttweaker_version}"

//  runtimeOnly "vazkii.patchouli:Patchouli:${patchouli_version}"
    runtimeOnly "mezz.jei:jei-${minecraft_version}-neoforge:${jei_version}"

    compileOnly "mezz.jei:jei-${minecraft_version}-common-api:${jei_version}"
    compileOnly "mezz.jei:jei-${minecraft_version}-neoforge-api:${jei_version}"
}

java.withSourcesJar()

tasks.register('apiJar', Jar) {
    from(sourceSets.main.output) {
        include 'com/blakebr0/mysticalagriculture/api/**'
    }

    archiveClassifier = 'api'
}

artifacts {
    archives apiJar
}

tasks.withType(ProcessResources).configureEach {
    var replaceProperties = [
            mod_version            : version.split('-').last(),
            cucumber_version       : cucumber_version.split('-').last(),
    ]
    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

publishing {
    publications {
        maven(MavenPublication) {
            from components.java
            artifactId = 'mysticalagriculture'
        }
    }

    repositories {
        maven {
            name = 'GitHubPackages'
            url = 'https://maven.pkg.github.com/ethan-gallant/MysticalAgriculture'

            credentials {
                username = System.getenv('GPR_USER') ?: findProperty('gpr.user')
                password = System.getenv('GPR_TOKEN') ?: findProperty('gpr.key')
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}