license="MIT"

[[mods]]
    issueTrackerURL="https://github.com/BlakeBr0/MysticalAgriculture/issues"
    modId="mysticalagriculture"
    version="${mod_version}"
    displayName="Mystical Agriculture"
    updateJSONURL="https://api.blakesmods.com/v2/mods/mysticalagriculture/26.2/updates"
    displayURL="https://blakesmods.com/mystical-agriculture"
    # logoFile="examplemod.png"
    authors="BlakeBr0"
    credits="Mark719, xun468, Cavemanrockx"
    description='''
    Grow all your resources!
    '''

    [[dependencies.mysticalagriculture]]
        modId="neoforge"
        mandatory=true
        versionRange="[26.2.0.7-beta,)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalagriculture]]
        modId="minecraft"
        mandatory=true
        versionRange="[26.2,26.3)"
        ordering="NONE"
        side="BOTH"
    [[dependencies.mysticalagriculture]]
        modId="cucumber"
        mandatory=true
        versionRange="[${cucumber_version},)"
        ordering="NONE"
        side="BOTH"